name: dart_net_core_api
description: Dart Server for quick and easy API setups
version: 0.0.4
homepage: https://github.com/caseyryan/dart_net_core_api

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.2
  # mongo_dart: ^0.7.4+1
  reflect_buddy: ^1.7.1
  dart_core_orm:
    path: ./dart_core_orm
    # git:
    #   url: https://github.com/caseyryan/dart_core_orm.git
    #   ref: e8054e6e1f8b85d1b4b97f400a7e7709f1c5f4bf
  dio: ^4.0.0
  dio_cache_interceptor: ^3.0.3
  dio_cache_interceptor_file_store: ^1.0.0
  collection: ^1.15.0
  uuid: 3.0.5
  mime: ^1.0.4
  dart_jsonwebtoken: ^2.12.0
  args: ^2.4.2
  stream: ^3.0.0
  socket_io_common: ^2.0.1
  logging: ^1.0.0
  crypto: ^3.0.3
  image: ^4.1.3
  universal_html: ^2.2.4
  cron: ^0.6.1
  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
