name: dart_net_core_api
description: Dart Server for quick and easy API setups
version: 0.0.1
homepage: https://github.com/caseyryan/dart_net_core_api

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  path: ^1.8.0
  mongo_dart: ^0.7.4+1
  reflect_buddy: ^1.3.1
  dio: ^4.0.0
  dio_cache_interceptor: ^3.0.3
  dio_cache_interceptor_file_store: ^1.0.0
  collection: ^1.15.0
  uuid: 3.0.5
  mime: ^1.0.4
  dart_jsonwebtoken: ^2.12.0
  args: ^2.4.2
  stream: ^3.0.0
  socket_io_common: ^2.0.1
  logging: ^1.0.0
  crypto: ^3.0.3
  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
