name: dart_core_doc_viewer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  lite_state: ^3.2.1
  cupertino_icons: ^1.0.8
  dio: ^5.4.1
  dio_cache_interceptor: ^3.0.3
  dio_cache_interceptor_file_store: ^1.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  google_fonts: ^6.1.0
  flutter_highlighting: ^0.9.0+11.8.0
  figma_squircle: ^0.5.3
  lottie: ^2.7.0
  lite_forms:
    git:
      url: https://github.com/caseyryan/flutter_lite_forms.git
      ref: 69754a0869ad782c3bc917806a8f758ce1cc4933

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  json_annotation: ^4.8.1
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/svg/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
